version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: time-tracker
    image: time-tracker:develop
    volumes:
      - ./.env:/application/.env
    ports:
      - "127.0.10.5:8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - DB_URL=postgres://postgres:${DB_PASSWORD}@postgres:5432/postgres?sslmode=disable


  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
