# See: https://taskfile.dev/api/

version: "3"

tasks:
  migrate-new:
    aliases:
      - migrate new
    desc: "Migrate database new"
    cmds:
      - migrate create -ext sql -dir ./db/migrations -seq init

  migrate-up:
    aliases:
      - migrate up
    desc: "Migrate database up"
    cmds:
      - sh -c 'source .env && export $(cut -d= -f1 .env) && migrate -path ./db/migrations -database "$DB_URL" up'

  migrate-down:
    aliases:
      - migrate down
    desc: "Migrate database down"
    cmds:
      - sh -c 'source .env && export $(cut -d= -f1 .env) && migrate -path ./db/migrations -database "$DB_URL" down'
  docker:
    aliases:
      - docker
    desc: "Docker"
    cmds:
      - docker build -t time-tracker:develop .
  compose-up:
    aliases:
      - compose up
    desc: "Compose up"
    cmds:
      - docker-compose up -d
  compose-down:
    aliases:
      - compose down
    desc: "Compose down"
    cmds:
      - docker-compose down